import { type Html, html } from "@butter/core";
import type { Mould } from "./types.ts";

/** The page calls this "Moulds" — the shapes the same butter gets pressed into. */
export const MOULDS: {
  readonly heading: string;
  readonly deck: string;
  readonly intro: Html;
  readonly outro: Html;
} = {
  heading: "Moulds",
  deck: "Four shapes an app gets pressed into",

  intro: html(`
      <p>
        A mould does not change the butter. It decides what comes out — a stick, a pat, a
        wheel — from the same batch, on the same day.
      </p>
      <p>
        The layers underneath are identical in every repository. What sits on top of them is
        not, and in practice it has only ever been four things. Each one below is a shape an
        entry in <code>apps/*</code> gets pressed into, and each names the repositories it is
        pressed into today.
      </p>`),

  outro: html(`
      <p>
        The shape is chosen per app and never per repository. Every one of the four appears in
        more than one repository above, and one repository has all four of them at once — a
        document site, an offline app, an asset host and a bot, sharing a lockfile.
      </p>
      <p>
        Which is the argument for the layers underneath rather than an exception to them. The
        runtime, the layout, the compiler flags and the gate are the half that does not change
        when the surface does, and that is the half worth deciding once.
      </p>`),
};

/**
 * The four shapes, with the apps that are in them.
 *
 * `apps` is data and the body is prose, which is the same seam the rest of the
 * package runs on. Every entry points at a public repository — a shape nobody
 * can open is a claim rather than an example, which is why the private one is
 * not on this page.
 */
export const MOULDS_LIST: readonly Mould[] = [
  {
    shape: "The document",
    tag: "static · islands",
    apps: [
      {
        label: "SU-SRD/apps/srd",
        href: "https://github.com/SalvageUnion-io/SU-SRD/tree/main/apps/srd",
      },
      {
        label: "optfall/apps/site",
        href: "https://github.com/alxjrvs/optfall/tree/main/apps/site",
      },
    ],
    body: html(`
        <p>
          Most pages are documents, so most pages ship no JavaScript at all. The generator
          lives inside the app — an <code>ssg/</code> directory beside <code>src/</code>, not a
          framework in <code>package.json</code>. Vite builds the client bundle; then Bun
          imports each page module directly and React renders it to a string. There is no
          server bundle and no second resolver, so the thing that renders a page is the same
          thing that runs its tests.
        </p>
        <p>
          An island is the exception, and it is a component rather than a mode. A subtree that
          genuinely has state — a search field, a picker — is rendered as its own root, gets
          its props as JSON in an attribute, and pays for its own hydration. Everything around
          it emits no script tag. Rendering an island inside the page instead is the mistake
          worth knowing about: <code>useId</code> counts from the root it was rendered in, so
          the server and the client disagree about every <code>id</code> in the subtree, and a
          label ends up pointing at nothing.
        </p>`),
  },
  {
    shape: "The offline one",
    tag: "workbox · indexeddb",
    apps: [
      {
        label: "SU-SRD/apps/itun",
        href: "https://github.com/SalvageUnion-io/SU-SRD/tree/main/apps/itun",
      },
      {
        label: "SU-SRD/apps/srd",
        href: "https://github.com/SalvageUnion-io/SU-SRD/tree/main/apps/srd",
      },
      {
        label: "optfall/apps/site",
        href: "https://github.com/alxjrvs/optfall/tree/main/apps/site",
      },
    ],
    body: html(`
        <p>
          A service worker, generated by Workbox <em>after</em> the pages are on disk, because
          it globs whatever the rest of the build left there. This mould composes with the
          first rather than replacing it: a document site takes a worker without becoming an
          app.
        </p>
        <p>
          The two settings that matter are both refusals. Precache the shell — scripts, styles,
          fonts — and never the HTML, because a site of thousands of pages cannot ship itself
          to a visitor's disk on first load. And set no <code>navigateFallback</code>, so a
          page nobody has visited returns a 404 offline instead of resolving to a stale shell.
          A reference tool that answers confidently and wrongly is worse than one that says it
          does not know.
        </p>
        <p>
          The stateful shape goes further: IndexedDB as the store of record, with TanStack
          Router and Query above it, and the worker registered as
          <code>prompt</code> rather than <code>autoUpdate</code>. An auto-updating worker
          activates the moment it installs, claims the page that is already open, and clears
          the precache that page is still reading its chunks from — which looks exactly like a
          link that needs four refreshes.
        </p>`),
  },
  {
    shape: "The asset host",
    tag: "blobs · one function",
    apps: [
      {
        label: "optfall/apps/images",
        href: "https://github.com/alxjrvs/optfall/tree/main/apps/images",
      },
      {
        label: "SU-SRD/apps/su-assets",
        href: "https://github.com/SalvageUnion-io/SU-SRD/tree/main/apps/su-assets",
      },
    ],
    body: html(`
        <p>
          Bytes that cannot live in git — licensed artwork, a corpus that would be carried
          forever — get their own deployable, and it is the smallest thing in the repository: a
          <code>netlify.toml</code>, one function reading a Blobs store, and a
          <code>public/</code> holding a robots.txt. The build command is <code>true</code>.
        </p>
        <p>
          Being a separate site is the entire point. The site that renders the pages promises
          static output and no runtime, and serving images needs a runtime — so the runtime
          goes here, where losing it costs a rendering layer and nothing else. Every page still
          renders and every fact on it is still correct. The pictures are simply missing.
        </p>`),
  },
  {
    shape: "The headless one",
    tag: "no framework",
    apps: [
      {
        label: "randsum/apps/discord-bot",
        href: "https://github.com/RANDSUM/randsum/tree/main/apps/discord-bot",
      },
      {
        label: "SU-SRD/apps/discord-bot",
        href: "https://github.com/SalvageUnion-io/SU-SRD/tree/main/apps/discord-bot",
      },
      {
        label: "randsum/apps/cli",
        href: "https://github.com/RANDSUM/randsum/tree/main/apps/cli",
      },
    ],
    body: html(`
        <p>
          A bot has no surface, so it gets no framework: <code>discord.js</code> with nothing
          in between, bundled to a single file, running as a Render worker that has to hold
          exactly one instance — a gateway connection cannot be load-balanced, and a second
          one processes every event twice. A command line is the same shape with a different
          entry point and a <code>prepublishOnly</code> where the start command would be.
        </p>
        <p>
          Nothing here needs a router, a bundler config or a component, and the only decision
          in the mould is recognising that. It is the shape a framework tempts you into least
          and rewards you for least.
        </p>`),
  },
];
